CREATE TYPE public.account_type AS ENUM
    ('AA', 'TFA', 'TFM', 'ATFM', 'SM');

-- Table structure for table `Temples`
CREATE TABLE public.temples (
    temp_id INT GENERATED BY DEFAULT AS IDENTITY,
    temp_name VARCHAR(20) NOT NULL,
    temp_address VARCHAR(50) NOT NULL,
    temp_city VARCHAR(20) NOT NULL,
    temp_country VARCHAR(20) NOT NULL,,
    temp_bdate date NOT NULL,
    temp_ddate date NOT NULL,
    temp_phone VARCHAR(30) NOT NULL,
    temp_picture VARCHAR(50) NOT NULL,
    CONSTRAINT temp_pk PRIMARY KEY (temp_id)
);

INSERT INTO public.temples (temp_name, temp_address, temp_city,
temp_country, temp_bdate, temp_ddate, temp_phone, temp_picture )
VALUES
    (
    'Asunción', 'Avda Brasilia Esquina Avda España', 'Asunción', 'Paraguay', '02/03/2001', '05/19/2002', '(595) 21-216-9200', '\images\temples\paraguay.png' ),
    ('Buenos Aires', 'Aut. Tte. Gral. Riccheri N° 4955, Ciudad Evita', 'Buenos Aires', 'Argentina', '04/20/1983', '01/17/1986', '(54) 11-4693-9700', '\images\temples\buenos_aires.png'),
    ('Concepción', 'Pedro de Valdivia 1525', 'Concepción', 'Chile', '10/17/2015', '10/28/2018', '(56) 41-3834700', '\images\temples\concepcion.png'),
    ('Córdoba', 'Avenida Pedro Laplace 5637', 'Córdoba', 'Argentina', '10/30/2010', '05/17/2015', '(54) 354-340-6200', '\images\temples\cordoba.png'),
    ('Salta', 'Av. Ingeniero Mario Saul Banchik N° 6050', 'Salta', 'Argentina', '11/04/2020', '06/16/2024', '(54) 387-432-4300', '\images\temples\salta.png'),
    ('Santiago', 'Pocuro 1940', 'Santiago', 'Chile', '05/30/1981', '09/15/1983', '(56) 22-340-5070', '\images\temples\santiago.png')    

-- Table structure for table `Properties`
CREATE TABLE public.properties (
    prop_id INT GENERATED BY DEFAULT AS IDENTITY,
    prop_name VARCHAR(30) NOT NULL,
    prop_size FLOAT NOT NULL,
    prop_comments VARCHAR(400),
    temp_id INT NOT NULL,
    CONSTRAINT prop_pk PRIMARY KEY (prop_id)
);

INSERT INTO public.properties (prop_name, prop_size, prop_comments, temp_id)
VALUES
    (
    'Temple', '2000', '', 1
    ), (
    'Patron Housing', '2500', '', 1
    ), (
    'Missionary Housing', '1000', '', 1
    ), (
    'Distribution Center', '700', '', 1
    ), (
    'Temple', '2000', '', 2
    ), (
    'Patron Housing', '2500', '', 2
    ), (
    'Missionary Housing', '1000', '', 2
    ), (
    'Distribution Center', '700', '', 2
    ), (
    'Temple', '2000', '', 3
    ), (
    'Patron Housing', '2500', '', 3
    ), (
    'Missionary Housing', '1000', '', 3
    ), (
    'Distribution Center', '700', '', 3
    ), (
    'Temple', '2000', '', 4
    ), (
    'Patron Housing', '2500', '', 4
    ), (
    'Missionary Housing', '1000', '', 4
    ), (
    'Distribution Center', '700', '', 4
    ), (
    'Temple', '2000', '', 5
    ), (
    'Patron Housing', '2500', '', 5
    ), (
    'Missionary Housing', '1000', '', 5
    ), (
    'Distribution Center', '700', '', 5
    ), (
    'Temple', '2000', '', 6
    ), (
    'Patron Housing', '2500', '', 6
    ), (
    'Missionary Housing', '1000', '', 6
    ), (
    'Distribution Center', '700', '', 6
    ),

-- Create relationship between `Temples` and `Properties` tables
ALTER TABLE IF EXISTS public.properties
    ADD CONSTRAINT fk_temples FOREIGN KEY (temp_id)
    REFERENCES public.temples (temp_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION;

-- Table structure for table `Rooms`
CREATE TABLE public.room (
    room_id INT GENERATED BY DEFAULT AS IDENTITY,
    room_name CHARACTER VARYING NOT NULL,
    room_width FLOAT NOT NULL,
    room_large FLOAT NOT NULL,
    room_height FLOAT NOT NULL,
    room_floor FLOAT NOT NULL,
    room_comments CHARACTER VARYING NOT NULL,
    prop_id INT NOT NULL,
    roomtype_id INT NOT NULL,
    CONSTRAINT room_pk PRIMARY KEY (room_id)
);

-- Table structure for table `Room Type`
CREATE TABLE public.roomtype (
    roomtype_id INT GENERATED BY DEFAULT AS IDENTITY,
    roomtype_name CHARACTER VARYING NOT NULL,
    CONSTRAINT roomtype_pk PRIMARY KEY (roomtype_id)
);

-- Create relationship between `Properties` and `Rooms` tables
ALTER TABLE IF EXISTS public.room
    ADD CONSTRAINT fk_properties FOREIGN KEY (prop_id)
    REFERENCES public.properties (prop_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION;

-- Create relationship between `Rooms` and `Room Type` tables
ALTER TABLE IF EXISTS public.room
    ADD CONSTRAINT fk_roomtype FOREIGN KEY (roomtype_id)
    REFERENCES public.roomtype (roomtype_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION;

-- Data for table `Room Type`

    INSERT INTO PUBLIC.roomtype (roomtype_name)
    VALUES (
        'Circulation'
    ), (
        'Dinning Room'
    ), (
        'Kitchen Room'
    ), (
        'Bedroom'
    ), (
        'Living Room'
    ), ('
        Bathroom'
    ), (
        'Ordinances'
    ),(
        'Dressing Room'
    ), (
        'Mechanical Room'
    ), (
        'Mezzanine'
    ), (
        'Admin Office'
    ), (
        'Office'
    ), (
        'Work Shop'
    ), (
        'Laundry'
    ), (
        'Waiting Room'
    ), (
        'Services Room'
    ), (
        'Chapel'
    ), (
        'Baptistery'
    );

-- Table structure for table `inventory`
CREATE TABLE IF NOT EXISTS public.inventory (
    inv_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_number character varying NOT NULL,
    inv_name character varying NOT NULL,
    inv_description text NOT NULL,
    unittype_id INT NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

-- Table structure for table `unit type`
CREATE TABLE public.unittype (
    unittype_id INT GENERATED BY DEFAULT AS IDENTITY,
    unittype_name CHARACTER VARYING NOT NULL,
    CONSTRAINT unittype_pk PRIMARY KEY (unittype_id)
);

-- Data for table `Unit Type`

    INSERT INTO PUBLIC.unittype (unittype_name)
    VALUES (
        'foot'
    ), (
        'inch'
    ), (
        'yard'
    ), (
        'sqft'
    ), (
        'sqfd'
    ), (
        'in2'
    ), (
        'acre'
    ), (
        'each'
    );

-- Create relationship between `inventory` and `unit type` tables
ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT fk_unittype FOREIGN KEY (unittype_id)
    REFERENCES public.unittype (unittype_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION;

INSERT INTO public.inventory (inv_number, inv_name, inv_description, unittype_id)

VALUES
    (
    '1', 'Ceiling, Gypsum or Plaster, Painted', 'Description 1', 4),
    ('2', 'Ceiling, Wood', 'Description 2', 4),
    ('3', 'Ceiling, Adhered Acoustic Panel', 'Description 3', 4),
    ('4', 'Ceiling, Hanging Acoustic Panel', 'Description 4', 4),
    ('5', 'Ceiling, Acoustic Spray', 'Description 5', 4),
    ('6', 'Floor, Concrete', 'Description 6', 4),
    ('7', 'Floor, Vinyl Sheet', 'Description 7', 4),
    ('8', 'Floor, Wood', 'Description 8', 4),
    ('9', 'Floor, Marble', 'Description 9', 4),
    ('10', 'Floor, Terrazzo', 'Description 10', 4)
	;


-- Create table between `inventory` and `room inventory` tables
CREATE TABLE public.room_inventory (
    room_inv_id INT GENERATED BY DEFAULT AS IDENTITY,
    room_id INT NOT NULL,
    inv_id INT NOT NULL,
    roominv_quantity INT NOT NULL,
    roominv_description INT NOT NULL,
    CONSTRAINT room_inv_pk PRIMARY KEY (room_inv_id)
);

-- Create relations between room_inventory and the other tables

ALTER TABLE IF EXISTS public.room_inventory
    ADD CONSTRAINT fk_room_inventory FOREIGN KEY (room_id)
    REFERENCES public.room (room_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.room_inventory
    ADD CONSTRAINT fk_inventory FOREIGN KEY (inv_id)
    REFERENCES public.inventory (inv_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION;

-- Table structure for table `account`
CREATE TABLE IF NOT EXISTS public.account(
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'TFM'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);